language: python
python:
  - "3.6"
  - "3.5"
env:
  -DJANGO=2.1.7
install:
  - pip install -r requirements.txt
  - pip install coverage==4.5.1
script:
  - coverage run --source='.' manage.py test ensembl_production