language: python
sudo: required
dist: xenial
python:
  - "3.7"
env:
  -DJANGO=2.1.5
install:
  - pip install -r requirements.txt
  - pip install coverage==4.5.1
script:
  - coverage run --source='.' manage.py test ensembl_production