language: python
os: linux
dist: xenial
python:
  - "3.7"
  - "3.8"
  - "3.9"
services:
  - mysql
env:
  - DB=mysql DEBUG=f
before_script:
  - mysql -u root -e "CREATE USER 'ensembl'@'%' IDENTIFIED BY '';"
  - mysql -u root -e "CREATE USER 'ensro'@'%' IDENTIFIED BY '';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'ensembl'@'%';"
  - mysql -u root -e "GRANT ALL ON *.* TO 'ensro'@'%';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
install:
  - pip install -U setuptools
  - pip install --upgrade importlib-metadata
  - pip install -r requirements-dev.txt
script:
  - coverage run ./src/manage.py test ensembl.production.dbcopy.tests.tests
