# Generated by Django 3.2.11 on 2022-09-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_dbcopy', '0012_dcserver_host_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestjob',
            name='skip_optimize',
            field=models.BooleanField(default=False, verbose_name='Skip Target Optimize'),
        ),
        migrations.AlterField(
            model_name='requestjob',
            name='src_incl_db',
            field=models.TextField(max_length=2048, verbose_name='Included Db(s)'),
        ),
    ]
